---
title: |
  | 日本・バングラデシュ関係50年: 現状と課題
  | Japan-Bangladesh relationship at 50: Achievements and challenges
subtitle: 研究課題ID319
author: "成果検討分科会 伊藤成朗"
date: last-modified
date-format: "MMMM DD, YYYY, HH:MM ZZ"
execute:
  echo: false
engine: knitr
pdf-engine: lualatex
format:
  html:
    standalone: true
    embed-resources: true
    toc: true
    toc-location: left
    grid:
      margin-width: 350px
####  pdf: default
  docx: default
theme: 
  light: sky
  dark: darkly
title-block-banner: "#f0f3f5"
title-block-banner-color: "black"
callout-appearance: simple
callout-icon: false
bibliography: ../seiro.bib
link-citations: true
reference-location: margin
citation-location: margin
#### # quarto render Ito2024Apr.qmd
#### c:\seiro\languages\R\R-4.4.1\bin\x64\Rscript.exe -e "path <- 'c:/seiro/docs/personal/Miscelleneous/QuartoFiles/posts/Ito2024Apr/'; rmarkdown::render(paste0(path, 'Ito2024Apr.Rmd'), output_format = 'all')"
---
```{css CSS setting, echo=FALSE, results = "hide"}
.SeiroBenign {
  background-color: #FFEBCD;
  padding: 0.5em; /*文字まわり（上下左右）の余白*/
  /* border: 1px solid yellow; */
  /* font-weight: bold; */
}
.SeiroLightGreen {
  background-color: #D0F0C0; /* Tea green */
  padding: 0.5em; /*文字まわり（上下左右）の余白*/
  font-family: Noto S	ans;
  /* border: 1px solid yellow; */
  /* font-weight: bold; */
}
/* Define a margin before hX (header level X) element */
h1  {
  margin-top: 3ex;
  margin-bottom: 3ex;
  /* background: #c2edff; */ /*背景色*/
  padding: 0.5em;/*文字まわり（上下左右）の余白*/
}
h2  {
  margin-top: 2ex;
  margin-bottom: 2ex;
  padding: 0.5em;/*文字周りの余白*/
  color: #010101;/*文字色*/
  /* background: #eaf3ff; */ /*背景色*/
  /* border-bottom: solid 3px #516ab6; */ /*下線*/
}
li > ul {
    padding-left:25px;
}
li > ol {
    padding-left:25px;
}
```

<style type="text/css">
  body, td{
  font-size: 16pt;
}
</style>



# 成果概要


1. 日バングラ関係史^[こういう経緯でした、というカタログ的内容。なので、Research questionはなくても良いのでは? ]: 序.要約、独立(1.日, 2.バ)、3.経済関係、4.ODA、5.NGO、人材育成(6.日, 7.バ)、8.新たな国際情勢、9.和文バングラデシュ研究目録
1. (おそらく)非研究者を含む執筆陣

# 検討者指摘概要

## 各項目の評価

:::{style="line-height: 92%;caption-side: top;"}
```{r result table, warning = F}
library(tinytable)
library(data.table)
ktb <- fread("kentohyo_tableformat.prn", header = F, sep = "\t")
ktb0 <- unlist(ktb[grepl("内容|適切", V1), ])
ktb1 <- unlist(ktb[grepl("総論|先行|論旨|知見|長さ|表現", V1), ])
ktb2 <- ktb[!grepl("内容|適切|総論|先行|論旨|知見|長さ|表現", V1), ]
ktb2[, c("J1", "J2", "E1", "E2") := ""]
setnames(ktb2, "V1", "項目")
ktb2[c(2, 8, 13, 17, 22, 27, 34), J1 := "○"]
ktb2[c(2, 7, 12, 16, 22, 28, 33), J2 := "○"]
ktb2[c(seq(1, 25, 5), 26, 32), E1 := "○"]
ktb2[c(seq(3, 20, 5), 22, 29, 33), E2 := "○"]

kt <- tt(ktb2, caption = "各項目の評価")
rowlist <- list()
#### Need to split row group label 1 to two lines as it is too long
rowlist[[1]] <- 1
rowlist[[2]] <- 1
rg1 <- c("「総論」（として位置づけられる章）において" ,
  "問題意識または仮説が明確に提示されているか。")
for (i in 2:length(ktb1)) rowlist[[i+1]] <- 1+5*(i-1)
names(rowlist)[1:2] <- rg1
names(rowlist)[-(1:2)] <- ktb1[-1]
kt <- theme_tt(kt, theme = "void")
kt <- group_tt(kt, i = rowlist)
kt <- style_tt(kt, 
  i = kt@group_index_i,
  align = "l",
  color = "black",
  background = "e4ebfa",
  bold = F,
  line = NULL
)

ktb3 = copy(ktb2)
ktb3[, question := ""]
rg <- c(rg1, ktb1[-1])
ktb3[1, question := rg[1]]
ktb3[2, question := rg[2]]
for (i in 3:length(ktb1)) ktb3[1+5*(i-2), question := rg[i]]
for (i in 1:length(ktb1)) ktb3[1+5*(i-1), question := ktb1[i]]
setcolorder(ktb3, c("question", "項目", "J1", "J2", "E1", "E2"))
setnames(ktb3, c("項目", "評価段階", "日1", "日2", "英1", "英2"))
kt <- tt(ktb3, width = c(.4, .4, rep(.1, 4)),
  caption = "各項目の評価")
kt <- theme_tt(kt, theme = "void")
for (i in 1:length(ktb1))
  kt <- style_tt(kt, 
    i = 1 + (i-1)*5, j = 1,
    color = "black",
    background = "e4ebfa",
    rowspan = 3
  )
kt <- style_tt(kt, bootstrap_css_rule = "table{caption-side: top;}")
kt
```
:::


## 講評、個別指摘事項

1. 類書はない、存在価値あり^[全検討者]
1. Research questionへの疑問
   a. 前提とする認識は正しいか?^[英2、日1 ]

::: {.callout-note title='good relationship?' collapse='true'}
The book also assumes that the relationship between the two countries has always been "good." While this is likely true, interestingly, reports (Chapter 8) suggest that Japan's ranking as a country with a favorable impression is not as high as that of countries with one or more periods of conflict (such as the USA and China) and is instead similar to that of India. 
:::

   b. 扱っているのはWhyではなくHowでは?^[英2 ]

::: {.callout-note title='research question, intro (p.1)' collapse='true'}
> 50 years of diplomatic relations...Japan and Bangladesh have always maintained good relations...it is worth considering **why this has been possible,** given the fact that Japan is the only major diplomatic partner with which Bangladesh has consistently maintained good relations...
:::

   c. 本書の回答・解釈は何か^[英2 ]

::: {.callout-note title='overall answer?' collapse='true'}
序章

please clearly discuss the answers to the overall findings. 
:::


3. 内容として全体にまとまりがない^[日2 ]
   * ただし、全体として何かを示すという方向性の指摘はない
   * 各章を改稿すべきという指摘のみ
   * 削除も視野に検討: 9章
1. 一部の章では分析対象の延伸が望ましい^[英2、日2 ]
   a) 最近10年ではなく、可能な限り遡るべき: 3章
   a) 経済関係は他国も含めるべき: 3章
1. 章間で統一性がない
   a) 各章: 質・量ともに不均一^[英2、日2 ]
      * 2倍量: 2、4章&larr; 他章との差を縮めるべき
      * 明確に目的/結論がない: 序、3、4、5、7、8章
      * 問題意識や導入がない章がある: 「序章および各章」^[日1 ]
      * 第4章: 図表合計=37
   a) 体裁(参考文献の記載・引用方法、固有名詞)の不統一^[英2、日1、日2 ]
1. それ以前の推敲不足^[英2、日1、日2 ]
1. 引用が明示的ではない
   a) 無断引用による著作権侵害の疑い^[日1「図表を個人で作成するようにお願いしたい」、英2 ]: 5、8章
   a) 原典が機関名のみ^[日1、日2 ]: 3、4章

# 所感

## 判断

このまま研究会に送付

* 検討票の誤字脱字は検討者に修正依頼、修正完了

1. 検討者指摘の評価
   * 内容は正当
   * 対象・疑問は具体的
   * 表現は適切
1. 章を加えるべきという指摘はない
1. 先行文献との違いに関する指摘はない
   * 読者は先行文献を知りたいはず&rarr; 「序章で言及があると良い」と分科会から伝えるか?


## 感想

* 意図は良いが実行が悪い研究成果
* 専門書として表現方法、内容ともに完成度の低い成果
   * これを検討者に検討させるのか
   * これを日英両言語で出版するのか
   * カタログ的内容なのに専門書としての和文単行書で良いのか 
* 同一内容を4人に検討させるのは無駄
* 検討者の努力も濃淡がある
   * 特濃: 英検討者2(大幅加筆修正)
   * 濃: 日検討者2^[指摘の内容や対象が特定されていないこともあるが、すべて「B.任意」対応指定なので問題なし ](大幅加筆修正)
   * 中: 日検討者1(大幅加筆修正)
   * 特淡: 英検討者1(了承)
      * どこまで真剣に検討したか疑問


